Footer project text and logo
geeksforsocialchange/teamwilder pull request #45
Opened 2023-03-09 17:22 UTC by ivan-kocienski-gfsc

Fixes #26 

## Description

Footer has (rough) SVG logo and project text

@geeksforsocialchange/developers

2023-03-09 17:42 UTC, katjam commented
@ivan-kocienski-gfsc When I said any logo would do, I meant a generic svg, not one from another client. :)

2023-03-09 17:42 UTC, katjam commented
@undividual Do you have a TW logo to hand?

2023-03-09 17:45 UTC, katjam requested changes

2023-03-09 17:45 UTC, katjam commented on src/Theme/FooterTemplate.elm
>              [ text (t FooterText)
I think we should remove this h2. It was a placeholder so we could "see the footer"

2023-03-09 17:45 UTC, katjam commented on src/Theme/FooterTemplate.elm
> +        [ img [ src "/images/dfl-logo.svg" ] []
In the design, the text sits on top of the logo. Also see note about either using a dummy logo or one from their website or Emma.

2023-03-10 09:19 UTC, undividual commented
> 

To the best of my knowledge there is no TeamWilder logo. Would you like a Wildlife Trusts logo?
![index](https://user-images.githubusercontent.com/90701712/224276049-c9638324-5f39-45d8-9b5b-a7a5ac7dbca7.png)

2023-03-10 09:26 UTC, katjam commented
@undividual Yes, sorry that's what I meant. Do you have an svg?

2023-03-10 09:49 UTC, undividual commented
> @undividual Yes, sorry that's what I meant. Do you have an svg?

No — you'll see I've emailed them to ask!

2023-03-10 13:58 UTC, katjam approved these changes
Looks great!

2023-03-10 18:49 UTC, merged